### PR TITLE
Add PromptExplained

### PR DESCRIPTION
**Pull request by freddysampayo**
Added a prompt engineering site: PromptExplained.com

### CODE REVIEW

**Review by AngelM1014 — APPROVED** [review]

**Comment by kerbelp** [comment]
Thanks! I just updated the title.

**Comment by kerbelp** [comment]
@freddysampayo are you the creator of PromptExplained?
I created a twitter profile for ai-collection and I want to tweet about PromptExplained and mention the creator.

**Comment by freddysampayo** [comment]
Hi Pavel, Yes, I am. Go ahead and mention me, I'd truly appreciate the
support! 🙌.

I'm planning to add at least 10 prompts a week to the site deconstructing
each one of them.

Please send me you @Twitter profile and keep up the great work with
ai-collection!

Regards,

--
Freddy J. Sampayo

**Comment by kerbelp** [comment]
Thanks! is your twitter user name @freddysampayo? I'm not sure from the bio :)
I'll use @ai_collection_ for the tweets and my personal is @kerbelp

**Comment by kerbelp** [comment]
And thanks for the kind words 🙏

**Comment by freddysampayo** [comment]
Yes, it's @freddysampayo and when you wrote me, I realized that I haven't
created a twitter account for the website, so that's @PromptExplained

Thanks!

--
Freddy J. Sampayo

**Pull request merged**
