### PR TITLE
Add aipoemgenerator.org to Text category

### PR DESCRIPTION
**Pull request by sonoroboto**

### CODE REVIEW

**Comment by kerbelp** [comment]
Thanks 🙏

**Comment by kerbelp** [comment]
@sonoroboto  Looks like the website does not really work. When clicking on generating a poem, it gets 500 Internal Server Error.
I'll have to remove it.

**Comment by sonoroboto** [comment]
@kerbelp My apologies, there was an issue with the site but it's now corrected

**Comment by sonoroboto** [comment]
@kerbelp Thanks so much for your help! 🙂

**Pull request merged**
