### PR TITLE
Added: WiseGPT (Powered by DhiWise)

### PR DESCRIPTION
**Pull request by TheRakeshPurohit**
In all languages.

### CODE REVIEW

**Comment by TheRakeshPurohit** [comment]
Twitter handle: https://www.twitter.com/dhiwise

**Comment by TheRakeshPurohit** [comment]
@kerbelp Please review!

**Comment by kerbelp** [comment]
Hi thanks, looks great! you are welcome to submit your awesome app to our website as well

https://www.thataicollection.com/submit/

**Comment by TheRakeshPurohit** [comment]
Thank you so much!

**Pull request merged**
