### PR TITLE
Add CoverDesignAI

### PR DESCRIPTION
**Pull request by EyonJoshua91**

### CODE REVIEW

**Comment by kerbelp** [comment]
Thanks 🙏

**Comment by EyonJoshua91** [comment]
@kerbelp I have seen this is merged to master, but I didn't find CoverDesignAI now. What happens?

**Comment by kerbelp** [comment]
Hi @EyonJoshua91, sorry about it.
I have a process that translates the app to different languages and syncs with ai-collection.org.
It mistakenly removed CoverDesignAI when a newer app was added. I Fixed it.

**Comment by EyonJoshua91** [comment]
No problem, thanks

**Pull request merged**
