### PR TITLE
Add Blend & Blend Studio

### PR DESCRIPTION
**Pull request by Heedster**

### CODE REVIEW

**Comment by kerbelp** [comment]
Thanks 👍

**Comment by kerbelp** [comment]
@Heedster are you the creator of Blend?
I created a twitter profile for ai-collection and I want to tweet about Blend and mention the creator.

**Comment by Heedster** [comment]
Yes. I am one of the creators.

**Comment by kerbelp** [comment]
What is your twitter username? I would like to mention you in the post.

**Pull request merged**
