### PR TITLE
Add OneTone.ai & Rephrasee.com project

### PR DESCRIPTION
**Pull request by flpbalada**

### CODE REVIEW

**Comment by kerbelp** [comment]
Thanks for the PR! 🚀🤘

**Comment by kerbelp** [comment]
@flpbalada are you the creator of OneTone.ai & Rephrasee.com?
I created a twitter profile for ai-collection and I want to tweet about it and mention the creator.

**Comment by flpbalada** [comment]
Hi Pavel,Thank you for contacting me. Yes, I am the creator of Rephrasee.com and co-founder of Onetone.ai. Feel free to tweet about that.Best,FilipOn 10. 4. 2023, at 21:42, Pavel Kerbel ***@***.***> wrote:﻿
@flpbalada are you the creator of OneTone.ai & Rephrasee.com?
I created a twitter profile for ai-collection and I want to tweet about it and mention the creator.

**Comment by kerbelp** [comment]
I can't find @flpbalada username on twitter, do you use other handle? I would like to mention you if you are on twitter.

**Comment by flpbalada** [comment]
My twitter account is @FilipBalada12 😊On 11. 4. 2023, at 22:48, Pavel Kerbel ***@***.***> wrote:﻿
I can't find @flpbalada username on twitter, do you use other handle? I would like to mention you if you are on twitter.

**Pull request merged**
